import type { AssetClass } from './types'

export interface Security {
  name: string
  ticker: string
  assetClass: AssetClass
}

// ── Thai Mutual Funds ─────────────────────────────────────────────────────────
const THAI_FUNDS: Security[] = [
  { name: 'Kasikorn Cash Management', ticker: 'K-CASH', assetClass: 'fund' },
  { name: 'Kasikorn Master Pool', ticker: 'K-MP', assetClass: 'fund' },
  { name: 'Kasikorn SET Index', ticker: 'K-SET', assetClass: 'fund' },
  { name: 'Kasikorn Global Bond', ticker: 'K-GB', assetClass: 'fund' },
  { name: 'Kasikorn China A-Share', ticker: 'K-CHINA-A', assetClass: 'fund' },
  { name: 'Kasikorn US500', ticker: 'K-US500', assetClass: 'fund' },
  { name: 'Kasikorn Global Equity', ticker: 'K-GHEALTH', assetClass: 'fund' },
  { name: 'SCB SET Index', ticker: 'SCBSET', assetClass: 'fund' },
  { name: 'SCB Dollar Bond', ticker: 'SCBDB', assetClass: 'fund' },
  { name: 'SCB US Equity', ticker: 'SCBDNAQ', assetClass: 'fund' },
  { name: 'SCB Blockchain and Digital Assets', ticker: 'SCBblockchain', assetClass: 'fund' },
  { name: 'SCB Thai Equity', ticker: 'SCBTEQ', assetClass: 'fund' },
  { name: 'Bangkok Bank SET', ticker: 'BBLSET', assetClass: 'fund' },
  { name: 'Bangkok Bank Cash', ticker: 'BBLCASH', assetClass: 'fund' },
  { name: 'Krungthai SET Index', ticker: 'KTSET50', assetClass: 'fund' },
  { name: 'Krungthai China', ticker: 'KTCHINA', assetClass: 'fund' },
  { name: 'Krungthai Fixed Income', ticker: 'KTFIX', assetClass: 'fund' },
  { name: 'One ULT Equity', ticker: 'ONE-ULT-EQ', assetClass: 'fund' },
  { name: 'One S&P500', ticker: 'ONE-SP500', assetClass: 'fund' },
  { name: 'TMB S&P500', ticker: 'TMBSP500', assetClass: 'fund' },
  { name: 'TMB Global Income', ticker: 'TMBGINCOME', assetClass: 'fund' },
  { name: 'Phatra Global Bond', ticker: 'PHATRA-GB', assetClass: 'fund' },
  { name: 'Phatra US Equity', ticker: 'PHATRA-US', assetClass: 'fund' },
  { name: 'MFC SET Index', ticker: 'MFC-SET', assetClass: 'fund' },
  { name: 'MFC Bond', ticker: 'MFC-BOND', assetClass: 'fund' },
  { name: 'Tisco SET50', ticker: 'TISCOSH', assetClass: 'fund' },
  { name: 'Tisco Fixed Income', ticker: 'TISCOFP', assetClass: 'fund' },
  { name: 'UOB Smart China India', ticker: 'UOBSCI', assetClass: 'fund' },
  { name: 'Finansa Money Market', ticker: 'FMM', assetClass: 'fund' },
  { name: 'BBLAM Healthcare', ticker: 'BBLAHCARE', assetClass: 'fund' },
]

// ── Thai Stocks (SET / MAI) ───────────────────────────────────────────────────
export const THAI_STOCKS: Security[] = [
  { name: 'PTT (ปตท.)', ticker: 'PTT', assetClass: 'fund' },
  { name: 'CP ALL (ซีพี ออลล์)', ticker: 'CPALL', assetClass: 'fund' },
  { name: 'Delta Electronics (Thailand)', ticker: 'DELTA', assetClass: 'fund' },
  { name: 'Airports of Thailand (ท่าอากาศยานไทย)', ticker: 'AOT', assetClass: 'fund' },
  { name: 'Bangkok Dusit Medical Services (กรุงเทพดุสิตเวชการ)', ticker: 'BDMS', assetClass: 'fund' },
  { name: 'Advanced Info Service (แอดวานซ์ อินโฟร์ เซอร์วิส)', ticker: 'ADVANC', assetClass: 'fund' },
  { name: 'Gulf Energy Development', ticker: 'GULF', assetClass: 'fund' },
  { name: 'SCB X (เอสซีบี เอกซ์)', ticker: 'SCB', assetClass: 'fund' },
  { name: 'Kasikornbank (ธนาคารกสิกรไทย)', ticker: 'KBANK', assetClass: 'fund' },
  { name: 'Bangkok Bank (ธนาคารกรุงเทพ)', ticker: 'BBL', assetClass: 'fund' },
  { name: 'Krungthai Bank (ธนาคารกรุงไทย)', ticker: 'KTB', assetClass: 'fund' },
  { name: 'True Corporation', ticker: 'TRUE', assetClass: 'fund' },
  { name: 'Siam Cement (ปูนซิเมนต์ไทย)', ticker: 'SCC', assetClass: 'fund' },
  { name: 'CP Axtra (ซีพี แอ็กซ์ตร้า)', ticker: 'CPAXT', assetClass: 'fund' },
  { name: 'Central Pattana (เซ็นทรัลพัฒนา)', ticker: 'CPN', assetClass: 'fund' },
  { name: 'Central Retail Corporation', ticker: 'CRC', assetClass: 'fund' },
  { name: 'Minor International', ticker: 'MINT', assetClass: 'fund' },
  { name: 'Intouch Holdings', ticker: 'INTUCH', assetClass: 'fund' },
  { name: 'Bumrungrad Hospital (โรงพยาบาลบำรุงราษฎร์)', ticker: 'BH', assetClass: 'fund' },
  { name: 'Thai Oil (ไทยออยล์)', ticker: 'TOP', assetClass: 'fund' },
  { name: 'PTT Exploration and Production', ticker: 'PTTEP', assetClass: 'fund' },
  { name: 'PTT Global Chemical', ticker: 'PTTGC', assetClass: 'fund' },
  { name: 'Banpu (บ้านปู)', ticker: 'BANPU', assetClass: 'fund' },
  { name: 'Home Product Center (โฮม โปรดักส์)', ticker: 'HMPRO', assetClass: 'fund' },
  { name: 'Siam Global House', ticker: 'GLOBAL', assetClass: 'fund' },
  { name: 'BTS Group Holdings', ticker: 'BTS', assetClass: 'fund' },
  { name: 'Bangkok Expressway and Metro', ticker: 'BEM', assetClass: 'fund' },
  { name: 'Hana Microelectronics', ticker: 'HANA', assetClass: 'fund' },
  { name: 'KCE Electronics', ticker: 'KCE', assetClass: 'fund' },
  { name: 'TMBThanachart Bank (ทีเอ็มบีธนชาต)', ticker: 'TTB', assetClass: 'fund' },
  { name: 'Tisco Financial Group', ticker: 'TISCO', assetClass: 'fund' },
  { name: 'Energy Absolute (พลังงานบริสุทธิ์)', ticker: 'EA', assetClass: 'fund' },
  { name: 'B.Grimm Power', ticker: 'BGRIM', assetClass: 'fund' },
  { name: 'Land and Houses', ticker: 'LH', assetClass: 'fund' },
  { name: 'Charoen Pokphand Foods (เจริญโภคภัณฑ์อาหาร)', ticker: 'CPF', assetClass: 'fund' },
  { name: 'Carabao Group (คาราบาวกรุ๊ป)', ticker: 'CBG', assetClass: 'fund' },
  { name: 'Thai Union Group', ticker: 'TU', assetClass: 'fund' },
  { name: 'WHA Corporation', ticker: 'WHA', assetClass: 'fund' },
  { name: 'Berli Jucker', ticker: 'BJC', assetClass: 'fund' },
  { name: 'Bangkok Chain Hospital', ticker: 'BCH', assetClass: 'fund' },
  { name: 'Chularat Hospital', ticker: 'CHG', assetClass: 'fund' },
  { name: 'SCG Packaging', ticker: 'SCGP', assetClass: 'fund' },
  { name: 'Osotspa (โอสถสภา)', ticker: 'OSP', assetClass: 'fund' },
  { name: 'Muangthai Capital', ticker: 'MTC', assetClass: 'fund' },
  { name: 'Srisawad Corporation', ticker: 'SAWAD', assetClass: 'fund' },
  { name: 'Ngern Tid Lor (เงินติดล้อ)', ticker: 'TIDLOR', assetClass: 'fund' },
  { name: 'Krungthai Card (บัตรกรุงไทย)', ticker: 'KTC', assetClass: 'fund' },
  { name: 'AP (Thailand)', ticker: 'AP', assetClass: 'fund' },
  { name: 'Sansiri (แสนสิริ)', ticker: 'SIRI', assetClass: 'fund' },
  { name: 'Supalai (ศุภาลัย)', ticker: 'SPALI', assetClass: 'fund' },
  { name: 'Indorama Ventures', ticker: 'IVL', assetClass: 'fund' },
  { name: 'IRPC', ticker: 'IRPC', assetClass: 'fund' },
  { name: 'OR (PTT Oil and Retail Business)', ticker: 'OR', assetClass: 'fund' },
]

// ── Thai DR / DRx (Depositary Receipts) ───────────────────────────────────────
export const THAI_DRS: Security[] = [
  { name: 'Diamond ETF DR (Vietnam)', ticker: 'FUEVFVND01', assetClass: 'fund' },
  { name: 'VN30 ETF DR (Vietnam)', ticker: 'E1VFVN3001', assetClass: 'fund' },
  { name: 'Nasdaq 100 DR', ticker: 'NDX01', assetClass: 'fund' },
  { name: 'S&P 500 DR', ticker: 'SPX01', assetClass: 'fund' },
  { name: 'Hang Seng DR', ticker: 'HK01', assetClass: 'fund' },
  { name: 'Hang Seng Tech DR', ticker: 'HKTECH01', assetClass: 'fund' },
  { name: 'China CSI 300 DR', ticker: 'CN01', assetClass: 'fund' },
  { name: 'China Tech DR', ticker: 'CNTECH01', assetClass: 'fund' },
  { name: 'Alibaba DR', ticker: 'BABA80', assetClass: 'fund' },
  { name: 'Tencent DR', ticker: 'TENCENT80', assetClass: 'fund' },
  { name: 'Xiaomi DR', ticker: 'XIAOMI80', assetClass: 'fund' },
  { name: 'BYD DR', ticker: 'BYD80', assetClass: 'fund' },
  { name: 'Apple Inc. DRx', ticker: 'AAPL80X', assetClass: 'fund' },
  { name: 'NVIDIA DRx', ticker: 'NVDA80X', assetClass: 'fund' },
  { name: 'Tesla DRx', ticker: 'TSLA80X', assetClass: 'fund' },
  { name: 'Microsoft DRx', ticker: 'MSFT80X', assetClass: 'fund' },
  { name: 'Alphabet DRx', ticker: 'GOOG80X', assetClass: 'fund' },
  { name: 'Amazon DRx', ticker: 'AMZN80X', assetClass: 'fund' },
  { name: 'Meta Platforms DRx', ticker: 'META80X', assetClass: 'fund' },
  { name: 'SPDR S&P 500 ETF DRx', ticker: 'SPY80X', assetClass: 'fund' },
  { name: 'Invesco QQQ DRx', ticker: 'QQQ80X', assetClass: 'fund' },
]

// ── US Stocks ─────────────────────────────────────────────────────────────────
export const US_STOCKS: Security[] = [
  { name: 'Apple', ticker: 'AAPL', assetClass: 'stock' },
  { name: 'Microsoft', ticker: 'MSFT', assetClass: 'stock' },
  { name: 'NVIDIA', ticker: 'NVDA', assetClass: 'stock' },
  { name: 'Alphabet (Google)', ticker: 'GOOGL', assetClass: 'stock' },
  { name: 'Amazon', ticker: 'AMZN', assetClass: 'stock' },
  { name: 'Meta Platforms', ticker: 'META', assetClass: 'stock' },
  { name: 'Tesla', ticker: 'TSLA', assetClass: 'stock' },
  { name: 'Berkshire Hathaway', ticker: 'BRK.B', assetClass: 'stock' },
  { name: 'Broadcom', ticker: 'AVGO', assetClass: 'stock' },
  { name: 'JPMorgan Chase', ticker: 'JPM', assetClass: 'stock' },
  { name: 'Visa', ticker: 'V', assetClass: 'stock' },
  { name: 'ExxonMobil', ticker: 'XOM', assetClass: 'stock' },
  { name: 'UnitedHealth Group', ticker: 'UNH', assetClass: 'stock' },
  { name: 'Johnson & Johnson', ticker: 'JNJ', assetClass: 'stock' },
  { name: 'Walmart', ticker: 'WMT', assetClass: 'stock' },
  { name: 'Mastercard', ticker: 'MA', assetClass: 'stock' },
  { name: 'Procter & Gamble', ticker: 'PG', assetClass: 'stock' },
  { name: 'Home Depot', ticker: 'HD', assetClass: 'stock' },
  { name: 'Netflix', ticker: 'NFLX', assetClass: 'stock' },
  { name: 'AMD', ticker: 'AMD', assetClass: 'stock' },
  { name: 'Salesforce', ticker: 'CRM', assetClass: 'stock' },
  { name: 'Adobe', ticker: 'ADBE', assetClass: 'stock' },
  { name: 'Costco', ticker: 'COST', assetClass: 'stock' },
  { name: 'Disney', ticker: 'DIS', assetClass: 'stock' },
  { name: 'PayPal', ticker: 'PYPL', assetClass: 'stock' },
  { name: 'Intel', ticker: 'INTC', assetClass: 'stock' },
  { name: 'Coca-Cola', ticker: 'KO', assetClass: 'stock' },
  { name: 'PepsiCo', ticker: 'PEP', assetClass: 'stock' },
  { name: 'Pfizer', ticker: 'PFE', assetClass: 'stock' },
  { name: 'Bank of America', ticker: 'BAC', assetClass: 'stock' },
  { name: 'Goldman Sachs', ticker: 'GS', assetClass: 'stock' },
  { name: 'Palantir', ticker: 'PLTR', assetClass: 'stock' },
  { name: 'Uber', ticker: 'UBER', assetClass: 'stock' },
  { name: 'Airbnb', ticker: 'ABNB', assetClass: 'stock' },
  { name: 'Spotify', ticker: 'SPOT', assetClass: 'stock' },
  { name: 'Shopify', ticker: 'SHOP', assetClass: 'stock' },
  { name: 'Snowflake', ticker: 'SNOW', assetClass: 'stock' },
  { name: 'Cloudflare', ticker: 'NET', assetClass: 'stock' },
  { name: 'Datadog', ticker: 'DDOG', assetClass: 'stock' },
  { name: 'CrowdStrike', ticker: 'CRWD', assetClass: 'stock' },
  // ETFs
  { name: 'S&P 500 ETF (SPY)', ticker: 'SPY', assetClass: 'stock' },
  { name: 'S&P 500 ETF (VOO)', ticker: 'VOO', assetClass: 'stock' },
  { name: 'Nasdaq 100 ETF (QQQ)', ticker: 'QQQ', assetClass: 'stock' },
  { name: 'Total Market ETF (VTI)', ticker: 'VTI', assetClass: 'stock' },
  { name: 'Schwab US Dividend Equity (SCHD)', ticker: 'SCHD', assetClass: 'stock' },
  { name: 'First Trust Clean Edge Smart Grid (GRID)', ticker: 'GRID', assetClass: 'stock' },
  { name: 'VanEck Semiconductor (SMH)', ticker: 'SMH', assetClass: 'stock' },
  { name: 'Vanguard Total World Stock (VT)', ticker: 'VT', assetClass: 'stock' },
  { name: 'International ETF (VXUS)', ticker: 'VXUS', assetClass: 'stock' },
  { name: 'Emerging Markets ETF (VWO)', ticker: 'VWO', assetClass: 'stock' },
  { name: 'Gold ETF (GLD)', ticker: 'GLD', assetClass: 'stock' },
  { name: 'Bitcoin ETF (IBIT)', ticker: 'IBIT', assetClass: 'stock' },
  { name: 'iShares 20+ Year Treasury (TLT)', ticker: 'TLT', assetClass: 'stock' },
  { name: 'iShares 0-3 Month Treasury Bond ETF (SGOV)', ticker: 'SGOV', assetClass: 'stock' },
]

// ── Gold ─────────────────────────────────────────────────────────────────────
const GOLD_SECURITIES: Security[] = [
  { name: 'Gold Bar (สมาคมค้าทองคำ)', ticker: 'XAU-TH', assetClass: 'gold' },
  { name: 'Gold 96.5% (บาททอง)', ticker: 'BAHT-GOLD', assetClass: 'gold' },
  { name: 'Gold Futures (TFEX)', ticker: 'GF', assetClass: 'gold' },
  { name: 'SPDR Gold Shares ETF', ticker: 'GLD', assetClass: 'gold' },
  { name: 'iShares Gold Trust', ticker: 'IAU', assetClass: 'gold' },
  { name: 'Gold 99.99% (gram)', ticker: 'XAU', assetClass: 'gold' },
]

export const ALL_SECURITIES: Security[] = [
  ...THAI_FUNDS,
  ...THAI_STOCKS,
  ...THAI_DRS,
  ...US_STOCKS,
  ...GOLD_SECURITIES,
]

export function searchSecurities(query: string, assetClass: AssetClass): Security[] {
  if (!query || query.trim().length < 1) return []
  const q = query.toLowerCase()
  return ALL_SECURITIES.filter(
    (s) =>
      s.assetClass === assetClass &&
      (s.name.toLowerCase().includes(q) || s.ticker.toLowerCase().includes(q)),
  ).slice(0, 6)
}
