import type { SpendiaryData } from './types'

/** Build an ISO date N days from today, so demo data always looks fresh. */
function inDays(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

const today = new Date().toISOString().slice(0, 10)

export const seedData: SpendiaryData = {
  userName: 'Tester',
  monthlyIncome: 110_000,
  monthlyPersonal: 20_000,
  fixedCostItems: [
    { id: 'fc1', name: 'ผ่อนคอนโด & ค่าส่วนกลาง (Mortgage & CAM)', amount: 18_000 },
    { id: 'fc2', name: 'ให้คุณพ่อคุณแม่ (Family Allowance)', amount: 12_000 },
    { id: 'fc3', name: 'เบี้ยประกันสุขภาพและชีวิต (Health/Life Insurance)', amount: 4_500 },
    { id: 'fc4', name: 'ค่าเน็ต โทรศัพท์ & บริการรายเดือน (Utilities & Subs)', amount: 2_500 },
  ],
  cashAccounts: [
    {
      id: 'c-kbank',
      name: 'KBank Payroll (เงินเดือน & บัญชีหลัก)',
      balance: 52_000,
      currency: 'THB',
      category: 'spending',
      bankPreset: 'kbank',
      color: '#16a34a',
    },
    {
      id: 'c-scb',
      name: 'SCB Easy (ใช้จ่ายทั่วไป & QR)',
      balance: 24_500,
      currency: 'THB',
      category: 'spending',
      bankPreset: 'scb',
      color: '#7c3aed',
    },
    {
      id: 'c-kept',
      name: 'Kept by krungsri (Grow 2.22% เงินสำรอง)',
      balance: 180_000,
      currency: 'THB',
      category: 'emergency',
      bankPreset: 'kept',
      color: '#f59e0b',
      interestRate: 2.22,
      payoutSchedule: 'monthly',
      payoutMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
    {
      id: 'c-dime-save',
      name: 'Dime! Save (ดอกเบี้ย 3.0% เต็มเพดาน)',
      balance: 10_000,
      currency: 'THB',
      category: 'emergency',
      bankPreset: 'dime',
      color: '#10b981',
      interestRate: 3.0,
      maxEligibleBalance: 10_000,
      payoutSchedule: 'semi_annual',
      payoutMonths: [6, 12],
    },
    {
      id: 'c-innovestx',
      name: 'InnovestX Cash (รอจังหวะช้อนหุ้น)',
      balance: 45_000,
      currency: 'THB',
      category: 'invest',
      bankPreset: 'scb',
      color: '#7c3aed',
      interestRate: 1.15,
      payoutSchedule: 'semi_annual',
      payoutMonths: [6, 12],
    },
    {
      id: 'c-dime-fcd',
      name: 'Dime! FCD (ดอลลาร์สหรัฐ USD 5.0%)',
      balance: 1_250,
      currency: 'USD',
      category: 'invest',
      bankPreset: 'dime',
      color: '#10b981',
      interestRate: 5.0,
      payoutSchedule: 'monthly',
      payoutMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
    {
      id: 'c-sahakorn',
      name: 'สหกรณ์ออมทรัพย์ (Sahakorn Coop 4.25%)',
      balance: 260_000,
      currency: 'THB',
      category: 'locked',
      bankPreset: 'sahakorn',
      color: '#6366f1',
      interestRate: 4.25,
      payoutSchedule: 'annual',
      payoutMonths: [12],
    },
    {
      id: 'c-pvd',
      name: 'กองทุนสำรองเลี้ยงชีพ (PVD Money Market)',
      balance: 140_000,
      currency: 'THB',
      category: 'locked',
      bankPreset: 'pvd',
      color: '#64748b',
    },
  ],
  holdings: [
    // ── 1. Thai Assets / Mutual Funds (fund) ─────────────────────────
    {
      id: 'h-sp500',
      name: 'SCB S&P 500 Index Fund',
      ticker: 'SCBS&P500',
      assetClass: 'fund',
      tag: 'ดัชนีสหรัฐ',
      units: 4800,
      avgCost: 18.4,
      price: 22.85,
      totalThbInvested: 88_320,
      updatedAt: today,
    },
    {
      id: 'h-tech',
      name: 'K-Global Tech Fund',
      ticker: 'K-USA-A',
      assetClass: 'fund',
      tag: 'เทคโนโลยี',
      units: 3200,
      avgCost: 24.1,
      price: 23.90,
      totalThbInvested: 77_120,
      updatedAt: today,
    },
    {
      id: 'h-cpnreit',
      name: 'CPN Retail Growth Leasehold REIT',
      ticker: 'CPNREIT',
      assetClass: 'fund',
      tag: 'ปันผลสูง',
      units: 12000,
      avgCost: 10.40,
      price: 11.50,
      totalThbInvested: 124_800,
      paysDividend: true,
      expectedDps: 0.28,
      dividendMonths: [3, 6, 9, 12],
      defaultCashAccountId: 'c-scb',
      updatedAt: today,
    },

    // ── 2. US Stocks (stock) ──────────────────────────────────────────
    {
      id: 'h-aapl',
      name: 'Apple Inc.',
      ticker: 'AAPL',
      assetClass: 'stock',
      tag: 'Tech Giant',
      units: 35,
      avgCost: 6150,
      price: 7920,
      avgCostUsd: 175,
      avgCostThb: 6150,
      totalThbInvested: 215_250,
      totalUsdInvested: 6_125,
      paysDividend: true,
      expectedDps: 9.1,
      dividendMonths: [2, 5, 8, 11],
      defaultCashAccountId: 'c-dime-fcd',
      updatedAt: today,
    },
    {
      id: 'h-nvda',
      name: 'NVIDIA Corp.',
      ticker: 'NVDA',
      assetClass: 'stock',
      tag: 'AI & Chips',
      units: 50,
      avgCost: 3200,
      price: 4850,
      avgCostUsd: 91,
      avgCostThb: 3200,
      totalThbInvested: 160_000,
      totalUsdInvested: 4_550,
      updatedAt: today,
    },
    {
      id: 'h-msft',
      name: 'Microsoft Corp.',
      ticker: 'MSFT',
      assetClass: 'stock',
      tag: 'Cloud / AI',
      units: 20,
      avgCost: 13500,
      price: 15400,
      avgCostUsd: 385,
      avgCostThb: 13500,
      totalThbInvested: 270_000,
      totalUsdInvested: 7_700,
      paysDividend: true,
      expectedDps: 28.5,
      dividendMonths: [3, 6, 9, 12],
      defaultCashAccountId: 'c-dime-fcd',
      updatedAt: today,
    },

    // ── 3. Bitcoin / Crypto (crypto) ──────────────────────────────────
    {
      id: 'h-btc',
      name: 'Bitcoin',
      ticker: 'BTC',
      assetClass: 'crypto',
      tag: 'Digital Gold',
      units: 0.52,
      avgCost: 2_150_000,
      price: 2_920_000,
      totalThbInvested: 1_118_000,
      btcLocations: [
        { id: 'btc-loc-1', name: 'ColdCard / Hardware Wallet', satoshi: 32_000_000, thbSpent: 688_000 },
        { id: 'btc-loc-2', name: 'Bitkub Exchange', satoshi: 12_000_000, thbSpent: 258_000 },
        { id: 'btc-loc-3', name: 'Binance', satoshi: 8_000_000, thbSpent: 172_000 },
      ],
      updatedAt: today,
    },

    // ── 4. Physical & Paper Gold (gold) ──────────────────────────────
    {
      id: 'h-gold',
      name: 'ทองคำแท่ง 96.5% (Bullion & Savings)',
      ticker: 'GOLD',
      assetClass: 'gold',
      tag: 'Safe Haven',
      units: 30.488, // 2 บาททอง (15.244 g ต่อบาท)
      avgCost: 2800, // ~42,683 ฿/บาททอง
      price: 3150,   // ~48,018 ฿/บาททอง
      totalThbInvested: 85_366,
      goldLocations: [
        { id: 'gold-loc-1', name: 'ฮั่วเซ่งเฮง (HSH Gold Now)', grams: 15.244, thbSpent: 42_500 },
        { id: 'gold-loc-2', name: 'แม่ทองสุก (MTS Gold Saving)', grams: 15.244, thbSpent: 42_866 },
      ],
      updatedAt: today,
    },

    // ── 5. Real Estate (real_estate) ─────────────────────────────────
    {
      id: 'h-condo',
      name: 'The Base Sukhumvit (Rental Condo)',
      ticker: 'CONDO-BKK',
      assetClass: 'real_estate',
      tag: 'อสังหาปล่อยเช่า',
      units: 1,
      avgCost: 2_600_000,
      price: 2_850_000,
      totalThbInvested: 2_600_000,
      paysDividend: true,
      expectedDps: 11_500,
      dividendMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      defaultCashAccountId: 'c-kbank',
      updatedAt: today,
    },
  ],
  dcaPlans: [
    {
      id: 'd1',
      name: 'Daily Bitcoin Stacking',
      ticker: 'BTC',
      assetClass: 'crypto',
      frequency: 'daily',
      monthlyAmount: 300,
      dayOfMonth: 1,
      holdingId: 'h-btc',
      btcLocationId: 'btc-loc-1',
      confirmedDates: [inDays(-1), inDays(-2), inDays(-3)],
    },
    {
      id: 'd2',
      name: 'Weekly Gold DCA (ฮั่วเซ่งเฮง)',
      ticker: 'GOLD',
      assetClass: 'gold',
      frequency: 'weekly',
      monthlyAmount: 2_500,
      dayOfMonth: 1, // Every Monday
      holdingId: 'h-gold',
      goldLocationId: 'gold-loc-1',
      confirmedDates: [inDays(-7), inDays(-14)],
    },
    {
      id: 'd3',
      name: 'S&P 500 Index Fund',
      ticker: 'SCBS&P500',
      assetClass: 'fund',
      frequency: 'monthly',
      monthlyAmount: 18_000,
      dayOfMonth: 1,
      holdingId: 'h-sp500',
      confirmedDates: [inDays(-12)],
    },
    {
      id: 'd4',
      name: 'US Tech Leaders (NVDA)',
      ticker: 'NVDA',
      assetClass: 'stock',
      frequency: 'monthly',
      monthlyAmount: 12_000,
      dayOfMonth: 15,
      holdingId: 'h-nvda',
    },
    {
      id: 'd5',
      name: 'CPNREIT Reinvestment',
      ticker: 'CPNREIT',
      assetClass: 'fund',
      frequency: 'monthly',
      monthlyAmount: 4_000,
      dayOfMonth: 25,
      holdingId: 'h-cpnreit',
    },
    {
      id: 'd6',
      name: 'Emergency Cash Auto-Reserve',
      assetClass: 'cash',
      frequency: 'monthly',
      monthlyAmount: 5_000,
      dayOfMonth: 28,
      cashAccountId: 'c-kept',
      confirmedDates: [inDays(-15)],
    },
  ],
  transfers: [
    {
      id: 't1',
      recipient: 'คุณพ่อคุณแม่ (Family Allowance)',
      note: 'โอนรายเดือนสม่ำเสมอ',
      amount: 12_000,
      frequency: 'monthly',
      completed: 9,
      total: 12,
      expiryDate: inDays(82),
    },
    {
      id: 't2',
      recipient: 'กองทุนส่วนกลาง & เงินสำรองฉุกเฉิน (Reserve Fund)',
      note: 'Auto-save to savings',
      amount: 10_000,
      frequency: 'monthly',
      completed: 22,
      total: 24,
      expiryDate: inDays(58),
    },
    {
      id: 't3',
      recipient: 'สลากออมสิน / ออมระยะสั้น',
      amount: 3_000,
      frequency: 'weekly',
      completed: 46,
      total: 52,
      expiryDate: inDays(11),
    },
    {
      id: 't4',
      recipient: 'เบี้ยประกันสุขภาพและชีวิต (Muang Thai Life)',
      note: 'Term Insurance Premium',
      amount: 4_500,
      frequency: 'monthly',
      completed: 5,
      total: 6,
      expiryDate: inDays(19),
    },
  ],
  liabilities: [
    {
      id: 'l1',
      name: 'สินเชื่อคอนโด (SCB Home Loan - The Base)',
      category: 'mortgage',
      balance: 1_680_000,
      interestRate: 3.45,
      monthlyPayment: 11_500,
      lender: 'SCB',
      dueDay: 28,
      note: 'MRR - 2.5% ดอกเบี้ยคงที่โปรโมชั่น 3 ปีแรก',
      updatedAt: today,
    },
    {
      id: 'l2',
      name: 'บัตรเครดิต KBank OneSiam (ชำระเต็มจำนวน)',
      category: 'credit_card',
      balance: 18_450,
      monthlyPayment: 18_450,
      lender: 'KBank',
      dueDay: 15,
      note: 'ตัดบัญชีอัตโนมัติรอบบิลปัจจุบัน',
      updatedAt: today,
    },
  ],
  rebalanceMode: 'class',
  rebalanceTargets: {
    fund: 30,
    stock: 25,
    crypto: 20,
    gold: 10,
    real_estate: 15,
  },
  dividendRecords: [
    {
      id: 'div-seed-1',
      holdingId: 'h-cpnreit',
      holdingName: 'CPN Retail Growth Leasehold REIT',
      ticker: 'CPNREIT',
      assetClass: 'fund',
      paymentDate: inDays(-20),
      dps: 0.28,
      shares: 12000,
      grossAmount: 3360,
      taxRate: 0.10,
      taxAmount: 336,
      netAmount: 3024,
      cashAccountId: 'c-scb',
      cashAccountName: 'SCB Easy (ใช้จ่ายทั่วไป & QR)',
      note: 'ปันผลงวดผลการดำเนินงาน Q2',
      createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    },
    {
      id: 'div-seed-2',
      holdingId: 'h-condo',
      holdingName: 'The Base Sukhumvit (Rental Condo)',
      ticker: 'CONDO-BKK',
      assetClass: 'real_estate',
      paymentDate: inDays(-10),
      dps: 11500,
      shares: 1,
      grossAmount: 11500,
      taxRate: 0,
      taxAmount: 0,
      netAmount: 11500,
      cashAccountId: 'c-kbank',
      cashAccountName: 'KBank Payroll (เงินเดือน & บัญชีหลัก)',
      note: 'รับค่าเช่าคอนโดประจำเดือน',
      createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    },
  ],
  holdingLogs: [
    {
      id: 'log-seed-1',
      timestamp: new Date(Date.now() - 86400000 * 15).toISOString(),
      action: 'add',
      holdingName: 'SCB S&P 500 Index Fund',
      ticker: 'SCBS&P500',
      assetClass: 'fund',
      note: 'Initial position: 4,800 units @ ฿18.40',
      holdingId: 'h-sp500',
    },
    {
      id: 'log-seed-2',
      timestamp: new Date(Date.now() - 86400000 * 10).toISOString(),
      action: 'buy_more',
      holdingName: 'NVIDIA Corp.',
      ticker: 'NVDA',
      assetClass: 'stock',
      note: 'DCA Buy: 15 units @ ฿3,200 (+฿48,000)',
      holdingId: 'h-nvda',
    },
    {
      id: 'log-seed-3',
      timestamp: new Date(Date.now() - 86400000 * 7).toISOString(),
      action: 'add',
      holdingName: 'Bitcoin',
      ticker: 'BTC',
      assetClass: 'crypto',
      note: 'Stacking: 0.32 BTC into ColdCard Hardware Wallet',
      holdingId: 'h-btc',
    },
    {
      id: 'log-seed-4',
      timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
      action: 'add',
      holdingName: 'ทองคำแท่ง 96.5% (Bullion & Savings)',
      ticker: 'GOLD',
      assetClass: 'gold',
      note: 'ออมทองคำแท่งฮั่วเซ่งเฮง 1 บาททอง (15.244 g @ ฿42,500)',
      holdingId: 'h-gold',
    },
    {
      id: 'log-seed-5',
      timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
      action: 'add',
      holdingName: 'The Base Sukhumvit (Rental Condo)',
      ticker: 'CONDO-BKK',
      assetClass: 'real_estate',
      note: 'บันทึกกรรมสิทธิ์อสังหาริมทรัพย์ปล่อยเช่า ฿2,600,000',
      holdingId: 'h-condo',
    },
  ],
  retirement: {
    monthlySpend: 45_000,
    retireAge: 55,
    deadAge: 85,
    inflationRate: 0.03,
    expectedReturn: 0.08,
    birthDate: '1995-06-15',
    withdrawalStrategy: 'drawdown',
  },
}
